- name: Installing packages using loops
  hosts: local
  connection: local
  tasks:
    - name: installing packages
      ansible.builtin.packages:
        name: "{{ item }}"
        state: present
      loop:
        - mysql
        - nginx
        - zip
