- name: Variable in Ansbile
  hosts: local
  connection: local
  become: yes
  vars:
    COURES: "DevOps, AWS"
    DURATION: "140 Hous"
    INSTRUCTOR: "Naga"
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Course is : {{COURES}}, duration is: {{DURATION:}}, and Trainser is {{INSTRUCTOR:}}"
