- name: Variable in Ansible
  hosts: web
  vars:
    COURSE: "DevOps, AWS"
    DURATION: "140 Hours"
    INSTRUCTOR: "Naga"
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Course is: {{ COURSE }}, duration is: {{ DURATION }}, and Trainer is {{ INSTRUCTOR }}"
